### ISSUE TITLE
empty gallery if js is off (bad for search engine robots?)

### ISSUE THREAD

**Issue by re8us** [MetalGuardian/yii2-fotorama-widget#1]
Hello!
Thanks for your widget!

Its handy to prepare array of images in code and use your widget by "second way".
But in this case images adding by script after load. And if i turn off javascript the gallery is empty, but fotorama has graceful degradation principles. I think you should generates image tags in widget for this case. And after all just init fotorama.

I think it's not good for SEO, isn't it?

Thanks!

**Comment by MetalGuardian** [comment]
Hi!
Can you show the example of such graceful degradation in fotorama? 
When I turn off javascript on the fotorama main page, the gallery is empty too.

This is possible to change behavior of the image tags generation, but without enabled js fotorama can not work anyway.

**Comment by re8us** [comment]
oops doesn't work in fotorama main page.

here: http://fotorama.io/customize/thumbnails/
turn off js and you see thumb with link to full picture (suddenly it hide other pictures by css...)

`<div class="fotorama" data-nav="thumbs">
<a href="1.jpg"><img src="1_thumb.jpg" width="144" height="96"></a>
<a href="2.jpg"><img src="2_thumb.jpg" width="64" height="128"></a>
</div>`

if js is on it generates gallery from given DOM elements inside div with parameters.

I think it is good practice to init fotorama from DOM elements instead of js array of objects.

Maybe i wrong, but i think it more valid and seo-friendly.
