### ISSUE TITLE
The file or directory to be published does not exist in yii2 v.2.0.13

### ISSUE THREAD

**Issue by idp001** [MetalGuardian/yii2-fotorama-widget#3]
After yii2 update to version 2.0.13, need change Asset url in FotoramaAsset.php file from  "public $sourcePath = '@vendor/bower/fotorama'" to  "public $sourcePath = '@vendor/bower-asset/fotorama'". After that, issues with "The file or directory to be published does not exist:" must gone. Sorry for my English :)

**Comment by MetalGuardian** [comment]
thanks, I will check it

**Comment by MetalGuardian** [comment]
it was already fixed in https://github.com/MetalGuardian/yii2-fotorama-widget/pull/2
I've updated version of the package to `1.0.1`
